version: '3.5'

services:

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"

  ganache:
    image: safe-ganache
    build:
      context: .
      dockerfile: docker/ganache/Dockerfile
    ports:
      - "8545:8545"
      
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  default:
    external:
      name: safe-relay
volumes:
  postgres-data:
