version: '3.5'

volumes:
  nginx-notify:

services:
  web-notification:
    build:
      context: safe-notification-service/
      dockerfile: docker/web/Dockerfile
    env_file:
      - ./safe-notification-service/.env
      - .env
    working_dir: /app
    ports:
      - 5679:5678
      - 8082:27017
    volumes:
      - ./safe-notification-service:/app
      - nginx-notify:/nginx
    command: docker/web/run_web.sh

  worker-notification: &worker
    build:
      context: safe-notification-service/
      dockerfile: docker/web/Dockerfile
    env_file:
      - ./safe-notification-service/.env
      - .env
    command: docker/web/celery/worker/run.sh
networks:
  default:
    external:
      name: safe-relay
