version: '3.5'

volumes:
  nginx-relay:

services:
  web-relay:
    build:
      context: safe-relay-service/
      dockerfile: docker/web/Dockerfile
    env_file:
      - safe-relay-service/.env
      - .env
    working_dir: /app
    ports:
      - 5678:5678
      - 8081:27017
    volumes:
      - ./safe-relay-service:/app
      - nginx-relay:/nginx
    command: docker/web/run_web.sh

  worker-relay: &worker
    build:
      context: safe-relay-service/
      dockerfile: docker/web/Dockerfile
    env_file:
      - safe-relay-service/.env
      - .env
    command: docker/web/celery/worker/run.sh

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
networks:
  default:
    external:
      name: safe-relay