version: '3'

volumes:
  nginx-relay:

services:
  nginx:
    image: nginx:1.13-alpine
    hostname: nginx
    ports:
      - "8000"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - nginx-relay:/nginx
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    working_dir: /app
    ports:
      - "27017"
    volumes:
      - nginx-relay:/nginx
    command: docker/web/run_web.sh

  worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
    command: docker/web/celery/worker/run.sh

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
networks:
  default:
    external:
      name: safe-relay